<?php

/**
 * @file
 * Modify existing items in batch
 *
 *
 *  Copyright 2017 Leiden University Library
 *
 *  This file is part of islandora_batch_modify.
 *
 *  islandora_batch_modify is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Permissions.
define('ISLANDORA_BATCH_MODIFY_FROM_ZIP', 'Batch Modify');

/**
 * Implements hook_menu().
 */
function islandora_batch_modify_menu() {
  return array(
    'islandora_batch_modify' => array(
      'title' => 'Batch Modify',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_batch_modify_import_form'),
      'file' => 'includes/zip_import.form.inc',
      'access arguments' => array(ISLANDORA_BATCH_MODIFY_FROM_ZIP),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_batch_modify_permission() {
  return array(
    ISLANDORA_BATCH_MODIFY_FROM_ZIP => array(
      'title' => t('Batch Modify'),
      'description' => t('Modify items in batch from a CSV or ZIP file'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function islandora_batch_modify_form_system_modules_alter(&$form, &$form_state, $form_id) {
  $form['modules']['Islandora Tools']['islandora_batch_modify']['links']['configure'] = array(
    '#type' => 'link',
    '#title' => t('Configure'),
    '#href' => 'islandora_batch_modify',
    '#options' => array(
      'attributes' => array(
        'class' => array('module-link', 'module-link-configure'),
        'title' => t('Setup a batch modify of items'),
      ),
    ),
  );
}
