<?php

/**
 * @file
 * Modify existing items in batch
 */

// Permissions.
define('ISLANDORA_BATCH_MODIFY_FROM_ZIP', 'Modify existing items in batch from zip file');

/**
 * Implements hook_menu().
 */
function islandora_batch_modify_menu() {
  return array(
    'islandora_batch_modify' => array(
      'title' => 'Modify existing items from a zip file',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_batch_modify_import_form'),
      'file' => 'includes/zip_import.form.inc',
      'access arguments' => array(ISLANDORA_BATCH_MODIFY_FROM_ZIP),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_batch_modify_permission() {
  return array(
    ISLANDORA_BATCH_MODIFY_FROM_ZIP => array(
      'title' => t('Modify existing items from zip file'),
      'description' => t('Modify existing items in batch from zip file'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function islandora_batch_modify_form_system_modules_alter(&$form, &$form_state, $form_id) {
  $form['modules']['Islandora Tools']['islandora_batch_modify']['links']['configure'] = array(
    '#type' => 'link',
    '#title' => t('Configure'),
    '#href' => 'islandora_batch_modify',
    '#options' => array(
      'attributes' => array(
        'class' => array('module-link', 'module-link-configure'),
        'title' => t('Setup a batch modify of existing items'),
      ),
    ),
  );
}
